articles/urls.py
from django.urls import path

from .views import (
  article_serch_view,
  article_create_view,
  article_detail_view
)

app_name = 'articles'

urlpatterns = [
  path('', article_serch_view, name='search'),
  path('create/', article_create_view, name='create'),
  path('<slug:slug>/', article_detail_view, name='detail')  
]

recipes/urls.py
from django.urls import path

from .views import (
  recipe_list_view,
  recipe_detail_view,
  recipe_create_view,
  recipe_update_view
)

app_name = 'recipes'

urlpatterns = [
  path('', recipe_list_view, name='list'),
  path('create/', recipe_create_view, name='create'),
  path('<int:id>/edit/', recipe_update_view, name='update'),
  path('<int:id>/', recipe_detail_view, name='detail')
]

trydjango/urls.py
from django.contrib import admin
from django.urls import path, include

from accounts.views import (
  login_view,
  logout_view,
  register_view
)
from .views import home_view


urlpatterns = [
  path('admin/', admin.site.urls),
  path('login/', login_view),
  path('logout/', logout_view),
  path('register/', register_view),
  path('', home_view),  
  path('articles/', include('articles.urls')),  
  path('pantry/recipes/', include('recipes.urls'))
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">  
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Try Django Tutorial</title>
</head>
<body>
  <h1>Hello World</h1>
  <form 
    action="/articles/" 
    method="GET" 
    autocomplete="off"
    style="margin-bottom: 40px;"
  >
    <input type="text" name="q" id="query" />    
    <button type="submit">Submit</button>
  </form>

  {% block content %}{% endblock %}
</body>
</html>

templates/home.html
{% extends "base.html" %}

{% block content %}
<h1>{{ object.title }} (id:{{ object.id }})</h1>
<h2>{{ object.content }}</h2>

<a href="{% url 'articles:create' %}">Create Article</a>

<ul>
  {% for item in object_list %}
    {% if item %}
      <li>
        <a href="{{ item.get_absolute_url }}">
          {{item.title}} - {{item.content}}
        </a>
      </li>
    {% endif %}
  {% endfor %}
</ul>
{% endblock %}